# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:35
from __future__ import unicode_literals

import ReKart.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=3, unique=True)),
                ('cname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='item_details',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=256)),
                ('itemprice', models.IntegerField()),
                ('description', models.TextField(max_length=1024)),
                ('returndays', models.IntegerField(default=0)),
                ('postingdate', models.DateField(default=datetime.date(2016, 4, 11))),
                ('itemage', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('image', models.FileField(upload_to=ReKart.models.get_upload_file_name)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.category', to_field='cid')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.cities')),
            ],
        ),
        migrations.CreateModel(
            name='kart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.item_details')),
                ('userid2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('pin', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=datetime.date(2016, 4, 11))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddField(
            model_name='item_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.states'),
        ),
        migrations.AddField(
            model_name='item_details',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='images',
            name='itemid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.item_details'),
        ),
        migrations.AddField(
            model_name='cities',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReKart.states'),
        ),
    ]
