# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReKart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_details',
            name='postingdate',
            field=models.DateField(default=datetime.date(2016, 4, 12)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2016, 4, 12)),
        ),
    ]
